### ISSUE TITLE
Rename to {api}-{language}-{title}

### ISSUE THREAD

**Issue by augustogoncalves** [Autodesk-Forge/forge-digital-twin#1]
maybe viewer-javascript-digital.twin ?

**Comment by petrbroz** [comment]
To be honest, that combination of dashes and dots is really weird. Do we really need to follow this? Why embedding APIs and languages in the name if we're using tags?

**Comment by augustogoncalves** [comment]
we can discuss that with the team, as of now all/most samples are using it...

**Comment by petrbroz** [comment]
Sure. Since this isn't really an official "sample" app (rather a sales demo), I can move it to my personal github account so that I don't introduce any inconsistent naming conventions. Let me know.

**Comment by petrbroz** [comment]
Closing this issue as we've discussed the new naming schema.
