### ISSUE TITLE
Help in configuration

### ISSUE THREAD

**Issue by AshrithSher** [Autodesk-Forge/forge-digital-twin#14]
First thanks a lot for making it open source. Thank you so much. 
I tried configuring it but when I run am getting only right side panel but not actual Jet Engine like it's not displaying dynamic data. Only static page is being displayed. I tried everything and followed your instructions but failed somewhere. 

Kindly please help me.

**Comment by petrbroz** [comment]
Thank you :) Have you followed the steps listed in https://github.com/Autodesk-Forge/forge-digital-twin#setup? Notice that you need to pass in an env. variable `FORGE_MODEL_URN` that should specify the [URN](https://forge.autodesk.com/en/docs/model-derivative/v2/tutorials/prepare-file-for-viewer/#step-1-convert-the-source-urn-into-a-base64-encoded-urn) of a model you want to display in the viewer. The jet engine sample file can be downloaded from https://knowledge.autodesk.com/support/inventor/downloads/caas/downloads/content/inventor-sample-files.html. You'll need to upload and translate it with your own Forge app credentials.
