### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by augustogoncalves** [Autodesk-Forge/forge-digital-twin#3]
any additional settings? or just an empty one?

any recommended provider (like mLab for mongo?)

https://github.com/Autodesk-Forge/forge-digital-twin#data-storage

**Comment by petrbroz** [comment]
I think the paragraph explains it clearly. By default (if no additional configuration is provided), the demo creates a local sqlite file. If you provide a `DATABASE_URL` env. variable with a postgres connection string, the demo will handle it, incl. creating/updating the tables.

**Comment by augustogoncalves** [comment]
>  the demo will handle it, incl. creating/updating the tables.

ok, perfect
