### ISSUE TITLE
Changing data in dynamic charts

### ISSUE THREAD

**Issue by 77-z** [Autodesk-Forge/forge-digital-twin#32]
How to fill in mongodb connection string?

How can I connect to a file in the database to display the data in the dynamic chart?

**Comment by petrbroz** [comment]
Connection string can be obtained by setting up a new MongoDB database. In the demo we're using a free tier of the [MongoDB Atlas](https://www.mongodb.com/atlas/database) service. The format of the connection string is explained here: https://www.mongodb.com/docs/manual/reference/connection-string/.

Regarding the real-time charts, these are actually showing random data generated on the client side (for example, [this code](https://github.com/Autodesk-Forge/forge-digital-twin/blob/master/public/scripts/performance.js#L150-L153) updates the engine speed data) so you don't need the MongoDB database for them.

**Comment by 77-z** [comment]
Thanks!
How can we change the data in the chart? Do you have any suggestions?

**Comment by petrbroz** [comment]
We're using the open source [Chart.js](https://www.chartjs.org) library, and you can find all the information about its data structures here: https://www.chartjs.org/docs/latest/general/data-structures.html.

In the demo, some charts are static (we just assign an array of numbers to the chart, like [here](https://github.com/Autodesk-Forge/forge-digital-twin/blob/master/public/scripts/performance.js#L116)) and some charts are dynamic (we're adding new values to the end of the chart data array, like [here](https://github.com/Autodesk-Forge/forge-digital-twin/blob/master/public/scripts/performance.js#L150-L153)).
