### ISSUE TITLE
The demo deployment seems to be down

### ISSUE THREAD

**Issue by somisawa** [Autodesk-Forge/forge-digital-twin#35]
This deployment currently cannot be reached. It occurs time out after a few minute loading.
https://forge-digital-twin.autodesk.io/

**Comment by petrbroz** [comment]
Hi @somisawa, thank you for the heads up! The link is supposed to be redirected to the new location - https://aps-digital-twin.autodesk.io - but for some reason the redirection isn't working. Let us look into that.
