### ISSUE TITLE
"Written by" section

### ISSUE THREAD

**Issue by augustogoncalves** [Autodesk-Forge/forge-digital-twin#7]
people use that name to ask direct questions :) 

I usually leave my twitter handle, [like this](https://github.com/Autodesk-Forge/bim360-csharp-issues#written-by)

**Comment by petrbroz** [comment]
Updated in https://github.com/Autodesk-Forge/forge-digital-twin/commit/2914491cc05fb586e03a00118acdf8912883f518.
