### ISSUE TITLE
Live sample

### ISSUE THREAD

**Issue by augustogoncalves** [Autodesk-Forge/forge-digital-twin#9]
shouldn't be http://forge-digital-twin.autodesk.io ?

both on top description & readme

**Comment by petrbroz** [comment]
I'm planning on updating these as soon as the app is live on that URL.

**Comment by augustogoncalves** [comment]
it's live, right? but for now redirects to heroku... later we remap to io server. but ok, makes sense

**Comment by petrbroz** [comment]
Sorry, I misunderstood. Yes, the app is available on http://forge-digital-twin.autodesk.io, but I was hoping to update the links when it's available on https://forge-digital-twin.autodesk.io.

**Comment by petrbroz** [comment]
The live sample url has been updated to http://forge-digital-twin.autodesk.io. Once it's available via https, we'll update it as well.
